#include <iostream>
#include<cmath>
using namespace std;
void nhap(float &x1,float &y1,float &x2,float &y2);
float kc(float x1,float y1,float x2,float y2);
void xuat(float kq);
int  main()
{	float x1,y1,x2,y2;
	nhap(x1,y1,x2,y2);
	float kq=kc(x1,y1,x2,y2);
	xuat(kq);

	return 0;
}
void nhap(float &x1,float &y1,float &x2,float &y2)
{		cout<<"Nhap x1 ";
		cin>>x1;
		cout <<"Nhap y1";
		cin>>y1;
		cout<< "nhap x2";
		cin>>x2;
		cout<<" nhap y2";
		cin>>y2;
}
float kc(float x1,float y1,float x2,float y2)
{
	return sqrt((x1-x2)*(x1-x2)+(y1-y2)*(y1-y2));
}

void xuat(float kq)
{
	cout<<"khoang cach cua 2 diem  da cho la"<<kq;
}
